apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: mogambo
  labels: { app: catalogue }
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels: { app: catalogue }
  template:
    metadata:
      labels: { app: catalogue }
    spec:
      serviceAccountName: catalogue
      automountServiceAccountToken: false
      containers:
        - name: catalogue
          image: andriohanania/catalogue:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          resources:
            requests: { cpu: "20m",  memory: "64Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
          readinessProbe:
            httpGet: { path: /health, port: 8081 }
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket: { port: 8081 }
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: mogambo
spec:
  type: ClusterIP
  selector: { app: catalogue }
  ports:
    - name: http
      port: 80
      targetPort: 8081
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalogue
  namespace: mogambo
  labels: { app: catalogue }
automountServiceAccountToken: false