apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: mogambo
  labels: { app: carts }
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels: { app: carts }
  template:
    metadata:
      labels: { app: carts }
    spec:
      serviceAccountName: carts
      automountServiceAccountToken: false
      containers:
        - name: carts
          image: andriohanania/carts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests: { cpu: "50m",  memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
          startupProbe:
            httpGet: { path: /actuator/health/liveness, port: 80 }
            periodSeconds: 5
            failureThreshold: 40
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 80 }
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 80 }
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: mogambo
spec:
  type: ClusterIP
  selector: { app: carts }
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts
  namespace: mogambo
  labels: { app: carts }
automountServiceAccountToken: false