apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: mogambo
  labels: { app: carts }
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels: { app: carts }
  template:
    metadata:
      labels: { app: carts }
    spec:
      containers:
        - name: carts
          image: andriohanania/carts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests: { cpu: "50m",  memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: carts
  namespace: mogambo
spec:
  type: ClusterIP
  selector: { app: carts }
  ports:
    - name: http
      port: 80
      targetPort: 80