apiVersion: ENC[AES256_GCM,data:05U=,iv:0LluquaDclIf5UZ9LXwPObCw7NFFV5TjbXscw4qI5W4=,tag:XsaptTN7vMPiiylvr/3fpA==,type:str]
kind: ENC[AES256_GCM,data:fhU8FOnS,iv:uWAtflViyObEZ+tmR8sSsWCLeb3KTi06nd7De3/fUAM=,tag:+IZ/Kt1rSM+dFt8QFDsL/w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TX9xoOPw/grw2h7x/KwNSfAKtRE=,iv:wrIoVJUsMzmFh2CswLNG/bUgVD3Hqo4yJ6+YysY1Xo0=,tag:twfKM2jGuAXQex2ytlMhNQ==,type:str]
    namespace: ENC[AES256_GCM,data:6XBW8e+yIA==,iv:WayT4xoUe/qfbx5iwXoaq59xUKsdR/MFLz5xoFRmDKU=,tag:R71KXLWzIARrgojfyV3nnw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:3XxVG7ndnpo=,iv:k1DPu4cS6baTY/G0Fu5SLYCPeeZRLKuFiweZo3TwD+E=,tag:ZIbF4sL3WXq1tsuFM6q7mg==,type:str]
type: ENC[AES256_GCM,data:XAMJDIwR,iv:z0CWJVOdYelf7Zsc8bqauFD6TJ7BimXLUYYmwdw+hJQ=,tag:1DdVD48WxutuDR7Ylt2TRw==,type:str]
#ENC[AES256_GCM,data:VqwY+E3hc0DQO3niy4L5g9P7tT6gMxPCzXtCZjEtVFmrrpMG5TE7,iv:L0JiwTFK/WhvbD6w4K4KwO412qSK321mnxbd7LKvBP8=,tag:8rHuKOsYt/fTmIZX3S124A==,type:comment]
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:H4hVmg==,iv:XeydjsbfzPbCmf3kPacexXblNVSQnlhffHBN1uyO2aM=,tag:jbIhfGeVk0GTvpt44S4OSQ==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:GCNPwqqERlQ=,iv:j7iRbTLZpiXO40n3+qwJtcuJ1L4LYRni4qmeR4jkcuY=,tag:puv9vZn7RZhPEJT4TL+32w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aTJmVkJTUW5lSUFneUtz
            bWtiMUFlVnppbW5pZ0paQkRqT3VSazNTa2hFCnZVaXorQlJIdFpNVjBFZ0d3Z3JF
            VllTYVAzU0Z2a25VdTVxRnFQdUc1ajgKLS0tIGdybS9oNzBtTFRhcW5mVTZNYkxZ
            bzZZV3JNaGg5dVNiMXdDUEVhS1RvNE0K+3QSHS1Zp7LSPYo/6nqNyomDrJiMexiR
            ZmzLMiREFiFKEZCCb0LRr+mIig56PkY3xm51syAsf0W+OAh+X21Ngg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h0uudxtc5r02ux66jhmrq3m9kmxec88dege7zfrmqun8deyr5uhqmwqvls
    lastmodified: "2026-06-06T10:44:59Z"
    mac: ENC[AES256_GCM,data:oK8nsixEVf7XVMTzvp+1ssVy8CegFPgllheHsV1Ehgp+Q1d+n8vW1+g6jJS63ge/B/EXMZhC++LpjucKAy+juZcIgtHCZ09SZ1g8ynNXhNkyiGX2sibE9D56GbWQ/Vd30jyw5r3kXLFZTG3dk39vGFN+PaPKoCNHYD27Y4e0OO0=,iv:TH437TaGrByt0sAOgdapD2rYsr4C5nAZLb6jgzr6PxU=,tag:e3p2RNUZLnb+Ze9s4dEl0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
