apiVersion: ENC[AES256_GCM,data:PBc=,iv:Bl82fyArCkN3hmtMuWCmPX1132OZpoLrLy1wf9hQ6/M=,tag:3CGzLo7GAPD//IjwPh9VcQ==,type:str]
kind: ENC[AES256_GCM,data:qSqA1nPY,iv:BhkDMxIvztoepedcwvS7QL3gFPr/U3iZKremFxm25KE=,tag:EfsI6speQa92zkY/qeoMKg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mSdC3emlDamP+q/yRMwV1+J3eiE=,iv:CbQuHsWSspD1oAyR02uwIpOi3fj159dmspDUNFQ9+T8=,tag:tmn0YwWiUFeGHsF95jtGjw==,type:str]
    namespace: ENC[AES256_GCM,data:7DzP5poUOw==,iv:O9DaYvtvH+Q5j+HHw3vCB3YfNpVIwvuBoCFBLRblquA=,tag:oWT3sVJYk01ma8yXPd3/EQ==,type:str]
    labels:
        app: ENC[AES256_GCM,data:WG54dGWg7a8=,iv:nFzfzxCyeYxVF2/HCnXfGAuDBCnAie/BVQdSlFZsH54=,tag:R58TYTj02LcRt6ZZxSc12A==,type:str]
type: ENC[AES256_GCM,data:PVaSbAZx,iv:RvmXUYFhvzbYBtk/7tJlOmAJA3qgKZFKVByqAX1/uu8=,tag:e8cVoeeqziFHq7hilasA8g==,type:str]
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:Thfddg==,iv:Lpu143kiQNJIyvS4DfF9NSzLGz7kmXF9MNVZcEUEEX0=,tag:jP4TJBKabl9hg6ycHbMmWw==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:mH6OgtQNq18=,iv:1D8oNesScsPI4LMuby4a/pHsTzPmI5krWIqe5tUd+Lw=,tag:cYR4qbQPRuEqiT/Y8/cGwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h0uudxtc5r02ux66jhmrq3m9kmxec88dege7zfrmqun8deyr5uhqmwqvls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsajU0djZHMnRFNHBHcktp
            a2N3Z210bjZXTmRVSHZDZTVDWURxZ1d3U1VrCmJmWmtjQnJZRlBjK2R2N0RzcExs
            TjFHeWNJb3kwdWNaTitJSk9yQjJ1RFEKLS0tIDhCVFZZWjJaYTh4cmxBREZweUdX
            eTQwQkQrR2NCTUx1S29XUTZOVC9KajAKMpQOkAuxXKYhEl4tV9bkFAvB7b0AVka2
            R6FDYI4YwYxOvjd6SxEdc+/zGaUaogjl5V8lt3HsTGOcWQR7VzGcWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T17:48:30Z"
    mac: ENC[AES256_GCM,data:AoUAXuV/ZZ70RgCFWYtklxahFiDc/LYJj4spVQZ4DStM1LMMysG3Kyc8FKH9JOD7bS8oEGC18AukbGT8TfkKsYmuTAY3fZMZi+EbOZ8rgbc6EG0y3MSrF+SeV6dGK//vqmZP6OcGoIa+SMgyMFqS8DmhjkRdXkFFAG0bCGdg16k=,iv:h6fGOn/Zw/BGl1YHCZEePz4AcWYCIGNg8mQrCGlQpbc=,tag:neZgDsKiEDCIc0lwci7kKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
