apiVersion: ENC[AES256_GCM,data:NRQ=,iv:elUKBW1ZFVjA0NBasGHXVxifyJExccJmr5Hun14z5Ec=,tag:8/aBBajsn0G4zNn6vszYuQ==,type:str]
kind: ENC[AES256_GCM,data:LbpVXXyf,iv:QodFHx1ENBBMU25yT8KgH1PDxeWBSCKegKJyH9BItMc=,tag:2WVxkeO4igq3oqT6qELQzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:C9Dl2lrApqDSIKVi1pzLie1OFa0=,iv:rgMJUG2D4szWRamFMbVmSJVSriHLolHjkG5ytfax2eI=,tag:dCUu8Ig0KL68HJo4g1swpQ==,type:str]
    namespace: ENC[AES256_GCM,data:8YInzZZ4Dg==,iv:o2tgNRrlWhvowXtSxksEXXjChGEBd/rL1NPEUSsw2gg=,tag:cygg+kvWn7hgba20xNIOGA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:HIyLh+yQ2NE=,iv:A7/y8LoS3hTnBZqmKVXnSkA0dU9WafOGui4eqytgr/4=,tag:0M/IfDAedcjf067ceW5uqw==,type:str]
type: ENC[AES256_GCM,data:p8+Wg3vo,iv:xFN4OUHVPQiRFgO3IdsgG2NsM+1RtgIPSemXJ3Rm/zU=,tag:o6VBGFiJygbvwRn/5wCX9g==,type:str]
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:13GBmQ==,iv:m1vu4rCWXYM7JfvEzgf+8uDCfwvqioifEaAnSjLqSYU=,tag:3AsrJHD1p2/vSvFoKTAe9g==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:SOWSfhTSnFA=,iv:NTSyS1Sl/gUOj/zYSpdDbRjvtncYTFVnf8VgnDtW0KU=,tag:hxbwXYoblrCjqhVFw5PbUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h0uudxtc5r02ux66jhmrq3m9kmxec88dege7zfrmqun8deyr5uhqmwqvls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZlRiUE5XRm1aekxITTZM
            WU94UFNiMExxdWkxakUvR0VReTkyNGtMK21jCmFRYU5WNVZrWUtreGkxKytlNTdh
            dm84OWZ0ZE5wVFBHVlR5N2xnQUMrNTAKLS0tIFhQT0p2ekY0eEphWTdFOHJNTGNO
            ODNjY0xaRzcyTFhDa3g0YVRyN210K0kKcaNG3rdMzioWK/ALbwpS8J6xJ1NpvxkM
            qr1H6sQoY2nvYyLKnjvKPWLLyXeoTqW4HVqgPhGw4j+gj+HrwCe6gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T18:04:02Z"
    mac: ENC[AES256_GCM,data:0HivwAiLFqKa2sxO8aJneraN/OsRRqtWRVovoIUrllUs5u79Igg+7vVvmVNmRlIs0HsKGgka2MNW66u+5kPH5CgYRq+7QpfnBwIxV7/RgLx/fMR7gm2jU+V7sk9rOTH1tHjDvs8YRH4BqThbV+IpbENf/Ju/50e6vHG4XPoALJg=,iv:PpVl32lot8zxMt+QgGQBBrge/raOaXAyRGsqD5YsaOc=,tag:6R1TNuWGWusFDr5B3PK42Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
