apiVersion: ENC[AES256_GCM,data:GNQ=,iv:oQgPlUPOEoKgsdxUpSF2WNdqnfxCbNlmcMjDbQB5UBg=,tag:UFAndjl6WFMYw+95Q/nKGw==,type:str]
kind: ENC[AES256_GCM,data:bpYYybbV,iv:fpgw5ApHcIO764KPD9BM91Z9waOhF23Ik1KIuWXLP4g=,tag:tyjCDpJIbOJpC0/lRbHhfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KcqmcTwVA9/iMA+bIHayrN3STNq3IaJf,iv:nmWBT32wHxRDX2wLn2m/J4+cjel5KLE+4ucYIghJvc0=,tag:jt0jGmRVD6lAEFrNMknLAQ==,type:str]
    namespace: ENC[AES256_GCM,data:li3FB1EX9A==,iv:VZAIzKg1KKPwQARgAfYBS5zlA9Bdz0f1KMIXUNrkT00=,tag:pR+QTaMGq43jPguIS42qHg==,type:str]
type: ENC[AES256_GCM,data:T/GkQ3Fz,iv:OYDfUSg1/xFdxol0cQ1j+aL+y90jKDqZBbQTUjSgk1E=,tag:SKw1ko6kjwt0nF4KpKRbqQ==,type:str]
stringData:
    MYSQL_ALLOW_EMPTY_PASSWORD: ENC[AES256_GCM,data:tGU+Jw==,iv:5/8GP1p1ivUBztE4a1l/pxDwfqQcOZeEpzFJwnLufow=,tag:fMiEd0mueySM2EtkHUJ95g==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:LQKuJqBEAw==,iv:EeKNTvs/7q45LWLGFYCsM6rL6UEB9j0RWiDDMMs+wG0=,tag:Xh1qdsjh6GQj6q00gP1OOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY3p1dmpHeFhMUUZvUGNn
            Rmg0S1lza0o1QVBVbWZib0hjZmpxQTdlRXd3Cit1SzZLZ3dscEFBa0FSUGM2TGdF
            NTdzQ0N0MW0rNktDNlprYldvU3BhNEEKLS0tIENheThtL0hWeGFoWU96Y0drRUVE
            Wngvbnovd3ZxVlEvMEZOYzZHaWR6dEkK1qdjaV7OfUsiW1xehdGRrhTTdqH9tmWk
            CoHBzK1lfeOC5yCgxPCMnkOWyKCPuL7D7tt3/es5P18JNbtkTrFI9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h0uudxtc5r02ux66jhmrq3m9kmxec88dege7zfrmqun8deyr5uhqmwqvls
    lastmodified: "2026-06-08T17:30:42Z"
    mac: ENC[AES256_GCM,data:8xIB+1hp5r93+lE+pum9Bs+twVsafhxlPYRXCTc0UDTKYP5x68X0ChnJmQ2RctrWLQnqYNslf4/uZc0DGyGiguPb/jo+Fb+u7Mz7U8fqnMvzrapEAW9QyOoP0nrBkdRM6/4tDtTcB4F48Izfc6vJju9FRTJPWxThmc7lVYWHRRU=,iv:2WFF/bPcxfMKZM5JLbjLQy6ER6TDFdCJtCIpr4y8YkI=,tag:89JnIq7b6DZtOgG/EeUrTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
